version: '2'
services:
  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-4.4-latest
    container_name: zabbix-agent
    restart: always
    privileged: true
    volumes:    
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "10053:10050"
    environment:
      - ZBX_HOSTNAME=zabbix-server
      - ZBX_SERVER_HOST=10.0.0.19
      - ZBX_SERVER_PORT=10051
